const students = [
  {
    "id": "202300001",
    "lastName": "Reyes",
    "firstName": "Maria",
    "middleName": "Cruz",
    "birthdate": "2002-05-15",
    "yearLevel": "3rd Year",
    "course": "BS in Computer Science",
    "admissionYear": 2023,
    "sex": "Female"
  },
  {
    "id": "202100002",
    "lastName": "Santos",
    "firstName": "Juan",
    "middleName": "Dela Cruz",
    "birthdate": "2001-08-22",
    "yearLevel": "4th Year",
    "course": "BS in Business Administration",
    "admissionYear": 2021,
    "sex": "Male"
  },
  {
    "id": "202400003",
    "lastName": "Bautista",
    "firstName": "Angela",
    "middleName": "Garcia",
    "birthdate": "2004-02-10",
    "yearLevel": "2nd Year",
    "course": "BA in Psychology",
    "admissionYear": 2024,
    "sex": "Female"
  },
  {
    "id": "202500004",
    "lastName": "Lim",
    "firstName": "Kevin",
    "middleName": "Tan",
    "birthdate": "2005-11-30",
    "yearLevel": "1st Year",
    "course": "BS in Accountancy",
    "admissionYear": 2025,
    "sex": "Male"
  },
  {
    "id": "202200005",
    "lastName": "Gomez",
    "firstName": "Sofia",
    "middleName": "Lopez",
    "birthdate": "2003-09-08",
    "yearLevel": "3rd Year",
    "course": "BS in Mechanical Engineering",
    "admissionYear": 2022,
    "sex": "Female"
  },
  {
    "id": "202000006",
    "lastName": "Cruz",
    "firstName": "Daniel",
    "middleName": "Reyes",
    "birthdate": "2000-01-18",
    "yearLevel": "4th Year",
    "course": "BS in Civil Engineering",
    "admissionYear": 2020,
    "sex": "Male"
  },
  {
    "id": "202300007",
    "lastName": "Lopez",
    "firstName": "Isabella",
    "middleName": "Santos",
    "birthdate": "2004-07-25",
    "yearLevel": "2nd Year",
    "course": "BS in Nursing",
    "admissionYear": 2023,
    "sex": "Female"
  },
  {
    "id": "202400008",
    "lastName": "Perez",
    "firstName": "Joshua",
    "middleName": "Lim",
    "birthdate": "2005-03-01",
    "yearLevel": "1st Year",
    "course": "BS in Information Technology",
    "admissionYear": 2024,
    "sex": "Male"
  },
  {
    "id": "202100009",
    "lastName": "Alvarez",
    "firstName": "Camille",
    "middleName": "Aquino",
    "birthdate": "2002-10-12",
    "yearLevel": "3rd Year",
    "course": "BS in Architecture",
    "admissionYear": 2021,
    "sex": "Female"
  },
  {
    "id": "202200010",
    "lastName": "De Guzman",
    "firstName": "Mark",
    "middleName": "Pascual",
    "birthdate": "2003-04-05",
    "yearLevel": "4th Year",
    "course": "BS in Hotel and Restaurant Management",
    "admissionYear": 2022,
    "sex": "Male"
  },
  {
    "id": "202000011",
    "lastName": "Aquino",
    "firstName": "Nicole",
    "middleName": "Ramos",
    "birthdate": "2000-09-20",
    "yearLevel": "4th Year",
    "course": "BS in Biology",
    "admissionYear": 2020,
    "sex": "Female"
  },
  {
    "id": "202500012",
    "lastName": "Gonzales",
    "firstName": "Matthew",
    "middleName": "Santos",
    "birthdate": "2006-06-19",
    "yearLevel": "1st Year",
    "course": "BS in Marketing Management",
    "admissionYear": 2025,
    "sex": "Male"
  },
  {
    "id": "202300013",
    "lastName": "Castro",
    "firstName": "Erika",
    "middleName": "Cruz",
    "birthdate": "2004-01-03",
    "yearLevel": "2nd Year",
    "course": "BS in Information Systems",
    "admissionYear": 2023,
    "sex": "Female"
  },
  {
    "id": "202200014",
    "lastName": "Diaz",
    "firstName": "Paolo",
    "middleName": "Reyes",
    "birthdate": "2003-07-14",
    "yearLevel": "3rd Year",
    "course": "BS in Pharmacy",
    "admissionYear": 2022,
    "sex": "Male"
  },
  {
    "id": "202100015",
    "lastName": "Domingo",
    "firstName": "Jessica",
    "middleName": "Lim",
    "birthdate": "2001-12-05",
    "yearLevel": "4th Year",
    "course": "BS in Nutrition and Dietetics",
    "admissionYear": 2021,
    "sex": "Female"
  },
  {
    "id": "202400016",
    "lastName": "Rodriguez",
    "firstName": "Chris",
    "middleName": "Santos",
    "birthdate": "2005-08-28",
    "yearLevel": "1st Year",
    "course": "BS in Civil Engineering",
    "admissionYear": 2024,
    "sex": "Male"
  },
  {
    "id": "202000017",
    "lastName": "Espiritu",
    "firstName": "Mia",
    "middleName": "Alvarez",
    "birthdate": "2000-04-11",
    "yearLevel": "4th Year",
    "course": "BA in Communication Arts",
    "admissionYear": 2020,
    "sex": "Female"
  },
  {
    "id": "202300018",
    "lastName": "Flores",
    "firstName": "Gabriel",
    "middleName": "Gomez",
    "birthdate": "2004-10-02",
    "yearLevel": "2nd Year",
    "course": "BS in Accountancy",
    "admissionYear": 2023,
    "sex": "Male"
  },
  {
    "id": "202200019",
    "lastName": "Garcia",
    "firstName": "Hannah",
    "middleName": "Hernandez",
    "birthdate": "2003-06-25",
    "yearLevel": "3rd Year",
    "course": "BS in Industrial Engineering",
    "admissionYear": 2022,
    "sex": "Female"
  },
  {
    "id": "202100020",
    "lastName": "Hernandez",
    "firstName": "Ivan",
    "middleName": "Lopez",
    "birthdate": "2002-03-09",
    "yearLevel": "4th Year",
    "course": "BS in Psychology",
    "admissionYear": 2021,
    "sex": "Male"
  },
  {
    "id": "202500021",
    "lastName": "Javier",
    "firstName": "Jasmine",
    "middleName": "Garcia",
    "birthdate": "2006-01-17",
    "yearLevel": "1st Year",
    "course": "BS in Pharmacy",
    "admissionYear": 2025,
    "sex": "Female"
  },
  {
    "id": "202400022",
    "lastName": "Lacsamana",
    "firstName": "Leo",
    "middleName": "Bautista",
    "birthdate": "2005-09-04",
    "yearLevel": "1st Year",
    "course": "BS in Computer Science",
    "admissionYear": 2024,
    "sex": "Male"
  },
  {
    "id": "202300023",
    "lastName": "Manalo",
    "firstName": "Alyssa",
    "middleName": "Domingo",
    "birthdate": "2004-06-13",
    "yearLevel": "2nd Year",
    "course": "BS in Mechanical Engineering",
    "admissionYear": 2023,
    "sex": "Female"
  },
  {
    "id": "202200024",
    "lastName": "Mendoza",
    "firstName": "Nathan",
    "middleName": "Espiritu",
    "birthdate": "2003-08-29",
    "yearLevel": "3rd Year",
    "course": "BS in Civil Engineering",
    "admissionYear": 2022,
    "sex": "Male"
  },
  {
    "id": "202100025",
    "lastName": "Morales",
    "firstName": "Olivia",
    "middleName": "Flores",
    "birthdate": "2002-02-07",
    "yearLevel": "4th Year",
    "course": "BS in Accountancy",
    "admissionYear": 2021,
    "sex": "Female"
  },
  {
    "id": "202000026",
    "lastName": "Navarro",
    "firstName": "Patrick",
    "middleName": "Garcia",
    "birthdate": "2000-11-21",
    "yearLevel": "4th Year",
    "course": "BS in Criminology",
    "admissionYear": 2020,
    "sex": "Male"
  },
  {
    "id": "202500027",
    "lastName": "Ocampo",
    "firstName": "Queenie",
    "middleName": "Hernandez",
    "birthdate": "2006-04-18",
    "yearLevel": "1st Year",
    "course": "BS in Nursing",
    "admissionYear": 2025,
    "sex": "Female"
  },
  {
    "id": "202400028",
    "lastName": "Pascual",
    "firstName": "Richard",
    "middleName": "Javier",
    "birthdate": "2005-07-06",
    "yearLevel": "1st Year",
    "course": "BS in Marine Engineering",
    "admissionYear": 2024,
    "sex": "Male"
  },
  {
    "id": "202300029",
    "lastName": "Quizon",
    "firstName": "Samantha",
    "middleName": "Lacsamana",
    "birthdate": "2004-03-29",
    "yearLevel": "2nd Year",
    "course": "BS in Accountancy",
    "admissionYear": 2023,
    "sex": "Female"
  },
  {
    "id": "202200030",
    "lastName": "Ramos",
    "firstName": "Timothy",
    "middleName": "Manalo",
    "birthdate": "2003-01-09",
    "yearLevel": "3rd Year",
    "course": "BS in Civil Engineering",
    "admissionYear": 2022,
    "sex": "Male"
  },
  {
    "id": "202100031",
    "lastName": "Santos",
    "firstName": "Valerie",
    "middleName": "Mendoza",
    "birthdate": "2002-08-01",
    "yearLevel": "4th Year",
    "course": "BA in Communication Arts",
    "admissionYear": 2021,
    "sex": "Female"
  },
  {
    "id": "202000032",
    "lastName": "Tan",
    "firstName": "Walter",
    "middleName": "Morales",
    "birthdate": "2001-05-18",
    "yearLevel": "4th Year",
    "course": "BS in Information Technology",
    "admissionYear": 2020,
    "sex": "Male"
  },
  {
    "id": "202500033",
    "lastName": "Uy",
    "firstName": "Xyza",
    "middleName": "Navarro",
    "birthdate": "2006-02-28",
    "yearLevel": "1st Year",
    "course": "BS in Architecture",
    "admissionYear": 2025,
    "sex": "Female"
  },
  {
    "id": "202400034",
    "lastName": "Velasco",
    "firstName": "Yuri",
    "middleName": "Ocampo",
    "birthdate": "2005-10-15",
    "yearLevel": "1st Year",
    "course": "BS in Mechanical Engineering",
    "admissionYear": 2024,
    "sex": "Male"
  },
  {
    "id": "202300035",
    "lastName": "Villanueva",
    "firstName": "Zoe",
    "middleName": "Pascual",
    "birthdate": "2004-04-07",
    "yearLevel": "2nd Year",
    "course": "BS in Computer Science",
    "admissionYear": 2023,
    "sex": "Female"
  },
  {
    "id": "202200036",
    "lastName": "Zapata",
    "firstName": "Aaron",
    "middleName": "Quizon",
    "birthdate": "2003-02-19",
    "yearLevel": "3rd Year",
    "course": "BS in Criminology",
    "admissionYear": 2022,
    "sex": "Male"
  },
  {
    "id": "202100037",
    "lastName": "Bantayan",
    "firstName": "Bianca",
    "middleName": "Ramos",
    "birthdate": "2002-09-03",
    "yearLevel": "4th Year",
    "course": "BS in Nursing",
    "admissionYear": 2021,
    "sex": "Female"
  },
  {
    "id": "202000038",
    "lastName": "Cordero",
    "firstName": "Carlo",
    "middleName": "Santos",
    "birthdate": "2001-07-27",
    "yearLevel": "4th Year",
    "course": "BS in Industrial Engineering",
    "admissionYear": 2020,
    "sex": "Male"
  },
  {
    "id": "202500039",
    "lastName": "De Vera",
    "firstName": "Chloe",
    "middleName": "Tan",
    "birthdate": "2006-05-11",
    "yearLevel": "1st Year",
    "course": "BS in Business Administration",
    "admissionYear": 2025,
    "sex": "Female"
  },
  {
    "id": "202400040",
    "lastName": "Enriquez",
    "firstName": "Dylan",
    "middleName": "Uy",
    "birthdate": "2005-01-23",
    "yearLevel": "1st Year",
    "course": "BA in Psychology",
    "admissionYear": 2024,
    "sex": "Male"
  },
  {
    "id": "202300041",
    "lastName": "Fabian",
    "firstName": "Felicity",
    "middleName": "Velasco",
    "birthdate": "2004-08-16",
    "yearLevel": "2nd Year",
    "course": "BS in Mechanical Engineering",
    "admissionYear": 2023,
    "sex": "Female"
  },
  {
    "id": "202200042",
    "lastName": "Galvez",
    "firstName": "Gino",
    "middleName": "Villanueva",
    "birthdate": "2003-03-08",
    "yearLevel": "3rd Year",
    "course": "BS in Computer Science",
    "admissionYear": 2022,
    "sex": "Male"
  },
  {
    "id": "202100043",
    "lastName": "Ignacio",
    "firstName": "Heidi",
    "middleName": "Zapata",
    "birthdate": "2002-06-10",
    "yearLevel": "4th Year",
    "course": "BS in Civil Engineering",
    "admissionYear": 2021,
    "sex": "Female"
  },
  {
    "id": "202000044",
    "lastName": "Joven",
    "firstName": "John",
    "middleName": "Bantayan",
    "birthdate": "2001-11-25",
    "yearLevel": "4th Year",
    "course": "BS in Accountancy",
    "admissionYear": 2020,
    "sex": "Male"
  },
  {
    "id": "202500045",
    "lastName": "King",
    "firstName": "Kyla",
    "middleName": "Cordero",
    "birthdate": "2006-03-03",
    "yearLevel": "1st Year",
    "course": "BS in Criminology",
    "admissionYear": 2025,
    "sex": "Female"
  },
  {
    "id": "202400046",
    "lastName": "Liwanag",
    "firstName": "Lawrence",
    "middleName": "De Vera",
    "birthdate": "2005-09-17",
    "yearLevel": "1st Year",
    "course": "BS in Business Administration",
    "admissionYear": 2024,
    "sex": "Male"
  },
  {
    "id": "202300047",
    "lastName": "Macaraeg",
    "firstName": "Micaela",
    "middleName": "Enriquez",
    "birthdate": "2004-05-21",
    "yearLevel": "2nd Year",
    "course": "BS in Nursing",
    "admissionYear": 2023,
    "sex": "Female"
  },
  {
    "id": "202200048",
    "lastName": "Narvaez",
    "firstName": "Nico",
    "middleName": "Fabian",
    "birthdate": "2003-01-26",
    "yearLevel": "3rd Year",
    "course": "BS in Electrical Engineering",
    "admissionYear": 2022,
    "sex": "Male"
  },
  {
    "id": "202100049",
    "lastName": "Ochavillo",
    "firstName": "Olivia",
    "middleName": "Galvez",
    "birthdate": "2002-07-08",
    "yearLevel": "4th Year",
    "course": "BS in Architecture",
    "admissionYear": 2021,
    "sex": "Female"
  },
  {
    "id": "202000050",
    "lastName": "Pineda",
    "firstName": "Peter",
    "middleName": "Ignacio",
    "birthdate": "2001-04-14",
    "yearLevel": "4th Year",
    "course": "BS in Information Technology",
    "admissionYear": 2020,
    "sex": "Male"
  },
  {
    "id": "202500051",
    "lastName": "Que",
    "firstName": "Queena",
    "middleName": "Joven",
    "birthdate": "2006-06-20",
    "yearLevel": "1st Year",
    "course": "BS in Computer Science",
    "admissionYear": 2025,
    "sex": "Female"
  },
  {
    "id": "202400052",
    "lastName": "Rivera",
    "firstName": "Ryan",
    "middleName": "King",
    "birthdate": "2005-02-09",
    "yearLevel": "1st Year",
    "course": "BS in Accountancy",
    "admissionYear": 2024,
    "sex": "Male"
  },
  {
    "id": "202300053",
    "lastName": "Salcedo",
    "firstName": "Sarah",
    "middleName": "Liwanag",
    "birthdate": "2004-10-27",
    "yearLevel": "2nd Year",
    "course": "BS in Nursing",
    "admissionYear": 2023,
    "sex": "Female"
  },
  {
    "id": "202200054",
    "lastName": "Salvador",
    "firstName": "Samuel",
    "middleName": "Macaraeg",
    "birthdate": "2003-05-13",
    "yearLevel": "3rd Year",
    "course": "BA in Communication Arts",
    "admissionYear": 2022,
    "sex": "Male"
  },
  {
    "id": "202100055",
    "lastName": "Tiongson",
    "firstName": "Tina",
    "middleName": "Narvaez",
    "birthdate": "2002-01-04",
    "yearLevel": "4th Year",
    "course": "BS in Civil Engineering",
    "admissionYear": 2021,
    "sex": "Female"
  },
  {
    "id": "202000056",
    "lastName": "Torres",
    "firstName": "Ulysses",
    "middleName": "Ochavillo",
    "birthdate": "2001-09-19",
    "yearLevel": "4th Year",
    "course": "BS in Industrial Engineering",
    "admissionYear": 2020,
    "sex": "Male"
  },
  {
    "id": "202500057",
    "lastName": "Valdez",
    "firstName": "Vanessa",
    "middleName": "Pineda",
    "birthdate": "2006-08-01",
    "yearLevel": "1st Year",
    "course": "BS in Information Technology",
    "admissionYear": 2025,
    "sex": "Female"
  },
  {
    "id": "202400058",
    "lastName": "Uy",
    "firstName": "Victor",
    "middleName": "Que",
    "birthdate": "2005-04-24",
    "yearLevel": "1st Year",
    "course": "BS in Accountancy",
    "admissionYear": 2024,
    "sex": "Male"
  },
  {
    "id": "202300059",
    "lastName": "Ventura",
    "firstName": "Willa",
    "middleName": "Rivera",
    "birthdate": "2004-12-05",
    "yearLevel": "2nd Year",
    "course": "BA in Psychology",
    "admissionYear": 2023,
    "sex": "Female"
  },
  {
    "id": "202200060",
    "lastName": "Yuson",
    "firstName": "Xavier",
    "middleName": "Salcedo",
    "birthdate": "2003-07-16",
    "yearLevel": "3rd Year",
    "course": "BS in Mechanical Engineering",
    "admissionYear": 2022,
    "sex": "Male"
  },
  {
    "id": "202100061",
    "lastName": "Zafra",
    "firstName": "Yvonne",
    "middleName": "Salvador",
    "birthdate": "2002-03-29",
    "yearLevel": "4th Year",
    "course": "BS in Architecture",
    "admissionYear": 2021,
    "sex": "Female"
  },
  {
    "id": "202000062",
    "lastName": "Bernardo",
    "firstName": "Zeke",
    "middleName": "Tiongson",
    "birthdate": "2001-01-11",
    "yearLevel": "4th Year",
    "course": "BS in Criminology",
    "admissionYear": 2020,
    "sex": "Male"
  },
  {
    "id": "202500063",
    "lastName": "Canlas",
    "firstName": "Andrea",
    "middleName": "Torres",
    "birthdate": "2006-10-02",
    "yearLevel": "1st Year",
    "course": "BS in Nursing",
    "admissionYear": 2025,
    "sex": "Female"
  },
  {
    "id": "202400064",
    "lastName": "Dela Cruz",
    "firstName": "Benjie",
    "middleName": "Valdez",
    "birthdate": "2005-06-25",
    "yearLevel": "1st Year",
    "course": "BS in Civil Engineering",
    "admissionYear": 2024,
    "sex": "Male"
  },
  {
    "id": "202300065",
    "lastName": "Estrella",
    "firstName": "Cindy",
    "middleName": "Uy",
    "birthdate": "2004-02-14",
    "yearLevel": "2nd Year",
    "course": "BS in Accountancy",
    "admissionYear": 2023,
    "sex": "Female"
  },
  {
    "id": "202200066",
    "lastName": "Fabregas",
    "firstName": "Dennis",
    "middleName": "Ventura",
    "birthdate": "2003-09-06",
    "yearLevel": "3rd Year",
    "course": "BS in Business Administration",
    "admissionYear": 2022,
    "sex": "Male"
  },
  {
    "id": "202100067",
    "lastName": "Gregorio",
    "firstName": "Elaine",
    "middleName": "Yuson",
    "birthdate": "2002-04-19",
    "yearLevel": "4th Year",
    "course": "BS in Pharmacy",
    "admissionYear": 2021,
    "sex": "Female"
  },
  {
    "id": "202000068",
    "lastName": "Hizon",
    "firstName": "Fred",
    "middleName": "Zafra",
    "birthdate": "2001-02-02",
    "yearLevel": "4th Year",
    "course": "BS in Information Technology",
    "admissionYear": 2020,
    "sex": "Male"
  },
  {
    "id": "202500069",
    "lastName": "Imperial",
    "firstName": "Gwen",
    "middleName": "Bernardo",
    "birthdate": "2006-12-08",
    "yearLevel": "1st Year",
    "course": "BS in Mechanical Engineering",
    "admissionYear": 2025,
    "sex": "Female"
  },
  {
    "id": "202400070",
    "lastName": "Jarin",
    "firstName": "Harold",
    "middleName": "Canlas",
    "birthdate": "2005-07-28",
    "yearLevel": "1st Year",
    "course": "BA in Psychology",
    "admissionYear": 2024,
    "sex": "Male"
  },
  {
    "id": "202300071",
    "lastName": "Lim",
    "firstName": "Irene",
    "middleName": "Dela Cruz",
    "birthdate": "2004-03-10",
    "yearLevel": "2nd Year",
    "course": "BS in Civil Engineering",
    "admissionYear": 2023,
    "sex": "Female"
  },
  {
    "id": "202200072",
    "lastName": "Mabini",
    "firstName": "Jerry",
    "middleName": "Estrella",
    "birthdate": "2003-11-23",
    "yearLevel": "3rd Year",
    "course": "BS in Computer Science",
    "admissionYear": 2022,
    "sex": "Male"
  },
  {
    "id": "202100073",
    "lastName": "Natividad",
    "firstName": "Karen",
    "middleName": "Fabregas",
    "birthdate": "2002-08-04",
    "yearLevel": "4th Year",
    "course": "BS in Accountancy",
    "admissionYear": 2021,
    "sex": "Female"
  },
  {
    "id": "202000074",
    "lastName": "Ochavillo",
    "firstName": "Lawrence",
    "middleName": "Gregorio",
    "birthdate": "2001-05-15",
    "yearLevel": "4th Year",
    "course": "BS in Industrial Engineering",
    "admissionYear": 2020,
    "sex": "Male"
  },
  {
    "id": "202500075",
    "lastName": "Pangilinan",
    "firstName": "Michelle",
    "middleName": "Hizon",
    "birthdate": "2006-01-26",
    "yearLevel": "1st Year",
    "course": "BA in Communication Arts",
    "admissionYear": 2025,
    "sex": "Female"
  },
  {
    "id": "202400076",
    "lastName": "Quijano",
    "firstName": "Nelson",
    "middleName": "Imperial",
    "birthdate": "2005-09-08",
    "yearLevel": "1st Year",
    "course": "BS in Business Administration",
    "admissionYear": 2024,
    "sex": "Male"
  },
  {
    "id": "202300077",
    "lastName": "Ramos",
    "firstName": "Paula",
    "middleName": "Jarin",
    "birthdate": "2004-06-21",
    "yearLevel": "2nd Year",
    "course": "BS in Computer Science",
    "admissionYear": 2023,
    "sex": "Female"
  },
  {
    "id": "202200078",
    "lastName": "Reyes",
    "firstName": "Quentin",
    "middleName": "Lim",
    "birthdate": "2003-04-12",
    "yearLevel": "3rd Year",
    "course": "BS in Criminology",
    "admissionYear": 2022,
    "sex": "Male"
  },
  {
    "id": "202100079",
    "lastName": "Salvador",
    "firstName": "Rachel",
    "middleName": "Mabini",
    "birthdate": "2002-12-03",
    "yearLevel": "4th Year",
    "course": "BS in Nursing",
    "admissionYear": 2021,
    "sex": "Female"
  },
  {
    "id": "202000080",
    "lastName": "Santiago",
    "firstName": "Steven",
    "middleName": "Natividad",
    "birthdate": "2001-08-27",
    "yearLevel": "4th Year",
    "course": "BS in Architecture",
    "admissionYear": 2020,
    "sex": "Male"
  },
  {
    "id": "202500081",
    "lastName": "Tabi",
    "firstName": "Theresa",
    "middleName": "Ochavillo",
    "birthdate": "2006-05-18",
    "yearLevel": "1st Year",
    "course": "BS in Civil Engineering",
    "admissionYear": 2025,
    "sex": "Female"
  },
  {
    "id": "202400082",
    "lastName": "Valdez",
    "firstName": "Vincent",
    "middleName": "Pangilinan",
    "birthdate": "2005-01-31",
    "yearLevel": "1st Year",
    "course": "BS in Mechanical Engineering",
    "admissionYear": 2024,
    "sex": "Male"
  },
  {
    "id": "202300083",
    "lastName": "Abad",
    "firstName": "Whitney",
    "middleName": "Quijano",
    "birthdate": "2004-09-13",
    "yearLevel": "2nd Year",
    "course": "BS in Computer Science",
    "admissionYear": 2023,
    "sex": "Female"
  },
  {
    "id": "202200084",
    "lastName": "Balagtas",
    "firstName": "Xander",
    "middleName": "Ramos",
    "birthdate": "2003-06-06",
    "yearLevel": "3rd Year",
    "course": "BS in Accountancy",
    "admissionYear": 2022,
    "sex": "Male"
  },
  {
    "id": "202100085",
    "lastName": "Calma",
    "firstName": "Yael",
    "middleName": "Reyes",
    "birthdate": "2002-03-20",
    "yearLevel": "4th Year",
    "course": "BS in Industrial Engineering",
    "admissionYear": 2021,
    "sex": "Female"
  },
  {
    "id": "202000086",
    "lastName": "David",
    "firstName": "Zac",
    "middleName": "Salvador",
    "birthdate": "2001-11-04",
    "yearLevel": "4th Year",
    "course": "BS in Criminology",
    "admissionYear": 2020,
    "sex": "Male"
  },
  {
    "id": "202500087",
    "lastName": "Esguerra",
    "firstName": "Abigail",
    "middleName": "Santiago",
    "birthdate": "2006-08-29",
    "yearLevel": "1st Year",
    "course": "BS in Nursing",
    "admissionYear": 2025,
    "sex": "Female"
  },
  {
    "id": "202400088",
    "lastName": "Fabian",
    "firstName": "Brian",
    "middleName": "Tabi",
    "birthdate": "2005-05-10",
    "yearLevel": "1st Year",
    "course": "BA in Psychology",
    "admissionYear": 2024,
    "sex": "Male"
  },
  {
    "id": "202300089",
    "lastName": "Guanlao",
    "firstName": "Catherine",
    "middleName": "Valdez",
    "birthdate": "2004-02-01",
    "yearLevel": "2nd Year",
    "course": "BS in Civil Engineering",
    "admissionYear": 2023,
    "sex": "Female"
  },
  {
    "id": "202200090",
    "lastName": "Henson",
    "firstName": "Dylan",
    "middleName": "Abad",
    "birthdate": "2003-10-14",
    "yearLevel": "3rd Year",
    "course": "BS in Business Administration",
    "admissionYear": 2022,
    "sex": "Male"
  },
  {
    "id": "202100091",
    "lastName": "Ignacio",
    "firstName": "Ellie",
    "middleName": "Balagtas",
    "birthdate": "2002-07-28",
    "yearLevel": "4th Year",
    "course": "BS in Information Technology",
    "admissionYear": 2021,
    "sex": "Female"
  },
  {
    "id": "202000092",
    "lastName": "Javier",
    "firstName": "Frank",
    "middleName": "Calma",
    "birthdate": "2001-04-09",
    "yearLevel": "4th Year",
    "course": "BS in Architecture",
    "admissionYear": 2020,
    "sex": "Male"
  },
  {
    "id": "202500093",
    "lastName": "King",
    "firstName": "Grace",
    "middleName": "David",
    "birthdate": "2006-12-02",
    "yearLevel": "1st Year",
    "course": "BS in Mechanical Engineering",
    "admissionYear": 2025,
    "sex": "Female"
  },
  {
    "id": "202400094",
    "lastName": "Liwanag",
    "firstName": "Harry",
    "middleName": "Esguerra",
    "birthdate": "2005-08-16",
    "yearLevel": "1st Year",
    "course": "BS in Civil Engineering",
    "admissionYear": 2024,
    "sex": "Male"
  },
  {
    "id": "202300095",
    "lastName": "Manalo",
    "firstName": "Isabel",
    "middleName": "Fabian",
    "birthdate": "2004-05-29",
    "yearLevel": "2nd Year",
    "course": "BS in Criminology",
    "admissionYear": 2023,
    "sex": "Female"
  },
  {
    "id": "202200096",
    "lastName": "Mendoza",
    "firstName": "Justin",
    "middleName": "Guanlao",
    "birthdate": "2003-03-07",
    "yearLevel": "3rd Year",
    "course": "BS in Accountancy",
    "admissionYear": 2022,
    "sex": "Male"
  },
  {
    "id": "202100097",
    "lastName": "Navarro",
    "firstName": "Kristine",
    "middleName": "Henson",
    "birthdate": "2002-01-19",
    "yearLevel": "4th Year",
    "course": "BS in Nursing",
    "admissionYear": 2021,
    "sex": "Female"
  },
  {
    "id": "202000098",
    "lastName": "Ocampo",
    "firstName": "Leo",
    "middleName": "Ignacio",
    "birthdate": "2000-11-25",
    "yearLevel": "4th Year",
    "course": "BS in Psychology",
    "admissionYear": 2020,
    "sex": "Male"
  },
  {
    "id": "202500099",
    "lastName": "Pascual",
    "firstName": "Monica",
    "middleName": "Javier",
    "birthdate": "2006-09-08",
    "yearLevel": "1st Year",
    "course": "BS in Accountancy",
    "admissionYear": 2025,
    "sex": "Female"
  },
  {
    "id": "202400100",
    "lastName": "Quizon",
    "firstName": "Nino",
    "middleName": "King",
    "birthdate": "2005-07-21",
    "yearLevel": "1st Year",
    "course": "BS in Information Technology",
    "admissionYear": 2024,
    "sex": "Male"
  }
];

module.exports = students;
